"""remove modified date

Revision ID: 1505048d97c
Revises: 5b665583002
Create Date: 2015-02-09 23:57:31.765136

"""

# revision identifiers, used by Alembic.
revision = '1505048d97c'
down_revision = '5b665583002'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'modified_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('modified_date', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
