"""adding modified date

Revision ID: 4da130be903f
Revises: 1505048d97c
Create Date: 2015-02-10 09:51:12.098275

"""

# revision identifiers, used by Alembic.
revision = '4da130be903f'
down_revision = '1505048d97c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('modified_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'modified_date')
    ### end Alembic commands ###
